name = "Cleite"
license = "MIT"
licenselink = "https://github.com/alandoyle/hugo-cleite-theme/blob/master/LICENSE"
description = "A simple, fast and responsive theme for Hugo with a strong focus on accessibility based on Terrassa."
homepage = "https://github.com/alandoyle/hugo-cleite-theme"
tags = ["blog", "clean", "personal", "company", "google analytics", "contact form","mobile", "modern", "accessibility", "font awesome"]
features = [
  "responsive design",
  "accessibility",
  "social icons",
  "contact form",
  "blog",
]
min_version = "0.41"

[author]
  name = "AlanDoyle (Alan Doyle)"
  homepage = "https://alandoyle.dev"
