baseurl = "/"
title = "Cleite"
author = "Alan Doyle (alandoyle)"
googleAnalytics = ""
defaultContentLanguage = "en"
paginate = 5

theme = "hugo-cleite-theme"
themesDir = "../.." # Not necessary on production sites

[params]
    author = "Alan Doyle"
    description = "Cleite is a simple, fast and responsive theme for Hugo with a strong focus on accessibility based on the Terrassa theme."
    favicon = "favicon.ico"
    logo = ""
    custom_css = ["css/custom.css"]

[params.hero]
    textColor = "" # Empty for default color

[params.cta] # Call To Action
    show = true
    cta = "Contact"
    link = "contact" # Relative URL

[params.separator] # Separators between sections on the home page
    show = true

[params.fa] # Font Awesome options
    version = "5.7.2"
    integrity = "sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP"

[params.form] # Contact form
    netlify = true
    action = "https://formspree.io/your@email.com"
    method = "POST"
    inputNameName = "name"
    inputNameLabel = "Name"
    inputNamePlaceholder = "Your name"
    inputEmailName = "email"
    inputEmailLabel = "Email"
    inputEmailPlaceholder = "Your email"
    inputMsgName = "message"
    inputMsgLabel = "Write something"
    inputMsgLength = 750
    inputSubmitValue = "Send"

[params.posts]
    showAuthor = true
    showDate = true
    showTags = true
    dateFormat = ":date_long"

[params.contact] # Contact info
    email = "example@gmail.com"
    phone = "xxx xxx xxx"
    skype = ""
    address = "419 Creek St. Revere, MA 02151"

[params.social]
    twitter = "https://twitter.com/john"
    facebook = "https://facebook.com/john"
    github = "https://github.com/john"
    gitlab = ""
    codepen = "https://codepen.io/john"
    instagram = "https://instagram.com/john"
    pinterest = ""
    youtube = ""
    linkedin = ""
    weibo = ""
    mastodon = ""
    tumblr = ""
    flickr = ""
    "500px" = ""

[params.copy] # Copyright
    copy = "2008-<NOW> - <TITLE>" # Empty for default content

[privacy]
    [privacy.googleAnalytics]
        anonymizeIP = true
        disable = false
        respectDoNotTrack = true
        useSessionStorage = false
    [privacy.instagram]
        disable = false
        simple = false
    [privacy.twitter]
        disable = false
        enableDNT = true
        simple = false
    [privacy.vimeo]
        disable = false
        simple = false
    [privacy.youtube]
        disable = false
        privacyEnhanced = true

[params.languageSwitcher]
    show = true

[languages]
    [languages.en]
        languageName = "en"
        weight = 1
        contentDir = "content/en"
      [languages.de]
        languageName = "de"
        weight = 2
        contentDir = "content/de"
        title = "Das ist der deutsche Titel"
        description = "Das ist die deutsche Beschreibung"
        [languages.de.params]
          [languages.de.params.form] # Translate contact form fields
            inputNameLabel = "Name"
            inputNamePlaceholder = "Dein Name"
            inputEmailLabel = "E-mail"
            inputEmailPlaceholder = "Deine E-Mail-Adresse"
            inputMsgLabel = "Schreib etwas"
            inputSubmitValue = "Abschicken"
            [languages.de.params.cta] # Translate Call To Action
                show = true
                cta = "Kontakt"
                link = "de/kontakt/" # Relative URL
